WebAPP/Models/FerryViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebAPP.Models
{
    public class FerryViewModel
    {
        private int _id;
        private string _name;
        private int _carCapacity;
        private int _passengerCapacity;
        private double _passengerPrice;
        private double _carPrice;

        [Range(0, 99999)]
        public int Id { get { return _id; } set { _id = value; } }

        [Required(ErrorMessage = "You forgot to enter your name")]
        [StringLength(120, MinimumLength = 2, ErrorMessage = "Name must be at least 2 characters")]
        public string Name { get { return _name; } set { _name = value; } }

        [Display(Name ="Maximum Car Capacity")]
        [Required(ErrorMessage ="You must set a maximum car capacity")]
        [Range(10, 99999)]
        public int CarCapacity { get { return _carCapacity; } set { _carCapacity = value; } }

        [Display(Name = "Maximum Passenger Capacity")]
        [Required(ErrorMessage = "You must set a maximum passenger capacity")]
        [Range(40,99999)]
        public int PassengerCapacity { get { return _passengerCapacity; } set { _passengerCapacity = value; } }


        [Display(Name = "Price per Passenger")]
        [Range(0, double.MaxValue)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:0.00}")]
        [RegularExpression("^\\$?(\\d{1,3},?(\\d{3},?)*\\d{3}(\\.\\d{1,3})?|\\d{1,3}(\\.\\d{2})?)$", ErrorMessage = "Price must be a number with a dot seperating decimals")]
        public double PassengerPrice { get { return _passengerPrice; } set { _passengerPrice = value; } }

        [Display(Name = "Price per Car")]
        [Range(0.00, double.MaxValue)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:0.00}")]
        [RegularExpression("^\\$?(\\d{1,3},?(\\d{3},?)*\\d{3}(\\.\\d{1,3})?|\\d{1,3}(\\.\\d{2})?)$", ErrorMessage ="Price must be a number with a dot seperating decimals")]
        public double CarPrice { get { return _carPrice; } set { _carPrice = value; } }
        }
}

WebAPP/Controllers/FerryController.cs
using Business_Logic;
using Data_Transfer_Objects.Model;
using Microsoft.AspNetCore.Mvc;
using WebAPP.Models;

namespace WebAPP.Controllers
{
    public class FerryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult OnActionSubmit(IFormCollection form)
        {
            string action = form["ferryAction"];
            int ferryID = 0;
            bool idGood = Int32.TryParse(form["ferryList"], out ferryID);
            if (action == null)
            {
                ViewBag.error = "There was an error with the selected action. Try again";
                return RedirectToAction("Index", "Home");

            }
            else
            {
                FerryBL ferryBL = new FerryBL();

                if (action.Equals("Book Passenger"))
                {
                    PassengerBooking passengerBooking = new PassengerBooking();
                    passengerBooking.ferryID = ferryID;
                    return View("BookPassenger", passengerBooking);
                }
                else if (action.Equals("Add Ferry"))
                {
                    FerryViewModel ferry = new FerryViewModel();
                    ferry.CarCapacity = 10;
                    ferry.PassengerCapacity = 40;
                    ferry.CarPrice = 197.00;
                    ferry.PassengerPrice = 99.00;
                    return View("Add", ferry);
                }
                else if (action.Equals("Remove Ferry"))
                {
                    if (idGood && ferryID != 0) { ferryBL.Remove(ferryID); }
                    
                    return RedirectToAction("Index", "Home");
                }
                else if (action.Equals("Update Ferry"))
                {
                    if (idGood && ferryID != 0) {
                        Console.WriteLine(ferryID);
                        Ferry ferry = ferryBL.Get(ferryID);
                        FerryViewModel ferryVM = new FerryViewModel();
                        ferryVM.Id = ferry.Id;
                        ferryVM.Name = ferry.Name;
                        ferryVM.CarCapacity = ferry.CarCapacity;
                        ferryVM.PassengerCapacity = ferry.PassengerCapacity;
                        ferryVM.CarPrice = ferry.CarPrice;
                        ferryVM.PassengerPrice = ferry.PassengerPrice;
                        return View("Update", ferryVM);
                    }
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ViewBag.error = "There was an error with the selected action. Try again";
                    return RedirectToAction("Index", "Home");
                }
            }
        }

        [HttpPost]
        public IActionResult BookNewPassenger(PassengerBooking booking)
        {
            if (ModelState.IsValid
                && booking.passengerName != null
                && booking.passengerGender != null
                && booking.passengerName.Trim().Length > 1
                && booking.passengerGender.Trim().Length > 1
                && booking.ferryID != 0
                )
            {
                Passenger passenger = new Passenger(0, booking.passengerName, booking.passengerGender);
                PassengerBL passengerBL = new PassengerBL();
                Passenger added = passengerBL.Add(passenger);
                FerryBL ferryBL = new FerryBL();
                Passenger reciept = ferryBL.AddPassenger(booking.ferryID, added.Id);
                return View("PassengerReciept", reciept);
            }
            else
            {
                ViewBag.error = "There was an error with the selected action. Try again";
                FerryBL ferryBL = new FerryBL();
                HashSet<Ferry> ferries = ferryBL.GetAll();
                return RedirectToAction("Index", "Home");
            }
        }


        [HttpPost]
        public IActionResult BookPassengerById(PassengerBooking booking)
        {
            if (
                booking.passengerID > 0
                && booking.ferryID != 0
                )
            {
                FerryBL ferryBl = new FerryBL();
                Passenger reciept = ferryBl.AddPassenger(booking.ferryID, booking.passengerID);
                return View("PassengerReciept", reciept);
            }
            else
            {
                ViewBag.error = "There was an error with the selected action. Try again";
                FerryBL ferryBL = new FerryBL();
                HashSet<Ferry> ferries = ferryBL.GetAll();
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        public IActionResult Add(FerryViewModel recieved)
        {
            if (ModelState.IsValid && recieved != null)
            {
                FerryBL ferryBL = new FerryBL();
                
                Ferry ferry = ferryBL.Add(new Ferry(0, recieved.Name, recieved.CarCapacity, recieved.PassengerCapacity, recieved.CarPrice, recieved.PassengerPrice));
                if (ferry != null) 
                { 
                    return View("ferryReciept", ferry); 
                } else { 
                    return RedirectToAction("Index", "Home"); 
                }

            } else
            {
                return View("Add");
            }
        }

        [HttpPost]
        public IActionResult Update(FerryViewModel recieved)
        {
            if (ModelState.IsValid && recieved != null)
            {
                FerryBL ferryBL = new FerryBL();

                Ferry ferry = ferryBL.Update(new Ferry(recieved.Id, recieved.Name, recieved.CarCapacity, recieved.PassengerCapacity, recieved.CarPrice, recieved.PassengerPrice));
                if (ferry != null)
                {
                    return View("ferryReciept", ferry);
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }

            }
            else
            {
                return View("Update");
            }
        }
    }
}

WebAPP/Views/Ferry/Add.cshtml
@using Data_Transfer_Objects.Model;

@*Shows a view for adding a ferry*@

@model FerryViewModel

@using (Html.BeginForm("Add", "Ferry", FormMethod.Post))
 {

    @await Html.PartialAsync("~/Views/partials/_ferryEditor.cshtml", Model)

    <input type="submit" value="Add" name="addFerry">
 }

<br />
<br />
@Html.ActionLink("Back to overview", "Index", "Home")

WebAPP/Views/Ferry/BookCar.cshtml
@using Data_Transfer_Objects.Model;

@*
    View for booking of a car with passengers
*@


@model Car

<h1>This function is currently not available</h1>
<p>Only booking of passengers are available in the demonstration WebApp.</p>

<br />
<br />
@Html.ActionLink("Back to overview", "Index", "Home")

WebAPP/Views/Ferry/BookPassenger.cshtml
@*
    View for booking a passenger, either through ID or by adding a new
*@

@model PassengerBooking

<h2>Book existing by id</h2>
@using (Html.BeginForm("BookPassengerByID", "Ferry", FormMethod.Post))
 {
     @Html.ValidationMessageFor(b => b.passengerID)
     @Html.LabelFor(b => b.passengerID)
     @Html.EditorFor(b => b.passengerID)

    @Html.HiddenFor(b => b.ferryID)
     <input type="submit" value="Book" name="findAndBook">
 }
 <h1>Or</h1>
 <h2>Book New</h2>
 @using (Html.BeginForm("BookNewPassenger", "Ferry", FormMethod.Post))
 {
     <div>
         @Html.ValidationMessageFor(b => b.passengerName)
         @Html.LabelFor(b => b.passengerName)
         @Html.EditorFor(b => b.passengerName)
     </div>
     <div>
         @Html.ValidationMessageFor(b => b.passengerGender)
         @Html.LabelFor(b => b.passengerGender)
         @Html.EditorFor(b => b.passengerGender)
     </div>
     
     <input type="submit" value="Book" name="BookNew">

     @Html.HiddenFor(b => b.ferryID)
 }

<br />
<br />
@Html.ActionLink("Back to overview", "Index", "Home")

WebAPP/Views/Ferry/PassengerReciept.cshtml
@using Data_Transfer_Objects.Model;

@*
    A reciepts shown after booking a passenger
*@

@model Passenger

<h2>Thank you for booking</h2>
<br />
<div>
@Html.LabelFor(p => p.Id)
@Html.DisplayFor(p => p.Id)
</div>
<div>
    @Html.LabelFor(p => p.Name)
    @Html.DisplayFor(p => p.Name)
</div>
<div>
    @Html.LabelFor(p => p.Gender)
    @Html.DisplayFor(p => p.Gender)
</div>

<br />
<br />
@Html.ActionLink("Back to overview", "Index", "Home")

WebAPP/Views/Ferry/Update.cshtml
@using Data_Transfer_Objects.Model;

@*
    Shows a view for updating the values of a ferry
*@

@model FerryViewModel

@using (Html.BeginForm("Update", "Ferry", FormMethod.Post))
{
    <div>
        @Html.LabelFor(f => f.Id)
        @Html.DisplayFor(f => f.Id)
        @Html.ValidationMessageFor(f => f.Id)
    </div>
    @await Html.PartialAsync("~/Views/partials/_ferryEditor.cshtml", Model)

    <input type="submit" value="Update" name="updateFerry">
}

<br />
<br />
@Html.ActionLink("Back to overview", "Index", "Home")

WebAPP/Views/Ferry/ferryReciept.cshtml
@using Data_Transfer_Objects.Model;

@*
    A reciept shown after adding or modifying a ferry
*@

@model Ferry

<h1>Ferry has been added</h1>
<br />
<div>
    @Html.LabelFor(f => f.Id)
    @Html.DisplayFor(f => f.Id)
</div>
<div>
    @Html.LabelFor(f => f.Name)
    @Html.DisplayFor(f => f.Name)
</div>
<div>
    @Html.LabelFor(f => f.CarCapacity)
    @Html.DisplayFor(f => f.CarCapacity)
</div>
<div>
    @Html.LabelFor(f => f.PassengerCapacity)
    @Html.DisplayFor(f => f.PassengerCapacity)
</div>
<div>
    @Html.LabelFor(f => f.CarPrice)
    @Html.DisplayFor(f => f.CarPrice)
</div>
<div>
    @Html.LabelFor(f => f.PassengerPrice)
    @Html.DisplayFor(f => f.PassengerPrice)
</div>

<br />
<br />
@Html.ActionLink("Back to overview", "Index", "Home")